### ISSUE TITLE
[InvalidArgumentException]   Could not find a version of package phpunit/php-file-iterator matching your minimum-stability (stable). Require it   with an explicit version constraint allowing its desired stability.

### ISSUE THREAD

**Issue by belougae** [sebastianbergmann/php-file-iterator#70] opened 2021-03-19 04:34 UTC
cztv@DESKTOP-GE3CB0C MINGW64 /c/wamp64/www/bluetv/dev/cztv_hudong_dev/cztv
$ composer require --dev phpunit/php-file-iterator

  [InvalidArgumentException]
  Could not find a version of package phpunit/php-file-iterator matching your minimum-stability (stable). Require it
  with an explicit version constraint allowing its desired stability.

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by sebastianbergmann** [comment] 2021-03-19 06:14
Probably a duplicate of #69.

**Closed by sebastianbergmann** 2021-03-19 06:14 UTC
